"""tema_ruleta

Revision ID: 1e54668b9dd5
Revises: 582326ba0696
Create Date: 2026-04-06 17:28:29.711311+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identificadores de revisión usados por Alembic
revision: str = '1e54668b9dd5'
down_revision: Union[str, None] = '582326ba0696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta migración a la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_solicitudes_referido_email_referido', table_name='solicitudes_referido')
    op.drop_index('ix_solicitudes_referido_id', table_name='solicitudes_referido')
    op.drop_table('solicitudes_referido')
    op.drop_index('ix_respuestas_encuesta_id', table_name='respuestas_encuesta')
    op.drop_table('respuestas_encuesta')
    op.drop_index('ix_administradores_id', table_name='administradores')
    op.drop_index('ix_administradores_username', table_name='administradores')
    op.drop_table('administradores')
    op.drop_index('ix_preguntas_encuesta_id', table_name='preguntas_encuesta')
    op.drop_table('preguntas_encuesta')
    op.add_column('ruletas', sa.Column('tema', sa.String(length=50), nullable=True))
    op.add_column('ruletas', sa.Column('tema_imagen', sa.String(length=500), nullable=True))
    op.add_column('ruletas', sa.Column('tema_color1', sa.String(length=7), nullable=True))
    op.add_column('ruletas', sa.Column('tema_color2', sa.String(length=7), nullable=True))
    op.add_column('ruletas', sa.Column('tema_color3', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios de esta migración (rollback)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ruletas', 'tema_color3')
    op.drop_column('ruletas', 'tema_color2')
    op.drop_column('ruletas', 'tema_color1')
    op.drop_column('ruletas', 'tema_imagen')
    op.drop_column('ruletas', 'tema')
    op.create_table('preguntas_encuesta',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('preguntas_encuesta_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('texto', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tipo', postgresql.ENUM('texto_libre', 'opcion_multiple', 'si_no', 'escala', name='tipopregunta'), autoincrement=False, nullable=True),
    sa.Column('opciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('obligatoria', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('activa', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('orden', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ruleta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ruleta_id'], ['ruletas.id'], name='preguntas_encuesta_ruleta_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='preguntas_encuesta_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_preguntas_encuesta_id', 'preguntas_encuesta', ['id'], unique=False)
    op.create_table('administradores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('superadmin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ultimo_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='administradores_pkey'),
    sa.UniqueConstraint('email', name='administradores_email_key')
    )
    op.create_index('ix_administradores_username', 'administradores', ['username'], unique=True)
    op.create_index('ix_administradores_id', 'administradores', ['id'], unique=False)
    op.create_table('respuestas_encuesta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pregunta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ruleta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('respuesta', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='respuestas_encuesta_cliente_id_fkey'),
    sa.ForeignKeyConstraint(['pregunta_id'], ['preguntas_encuesta.id'], name='respuestas_encuesta_pregunta_id_fkey'),
    sa.ForeignKeyConstraint(['ruleta_id'], ['ruletas.id'], name='respuestas_encuesta_ruleta_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='respuestas_encuesta_pkey')
    )
    op.create_index('ix_respuestas_encuesta_id', 'respuestas_encuesta', ['id'], unique=False)
    op.create_table('solicitudes_referido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referidor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email_referido', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('nombres_referido', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('ruleta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estatus', postgresql.ENUM('pendiente', 'aprobado', 'rechazado', name='estatusreferido'), autoincrement=False, nullable=False),
    sa.Column('motivo_rechazo', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('fecha_solicitud', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fecha_resolucion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='solicitudes_referido_cliente_id_fkey'),
    sa.ForeignKeyConstraint(['referidor_id'], ['clientes.id'], name='solicitudes_referido_referidor_id_fkey'),
    sa.ForeignKeyConstraint(['ruleta_id'], ['ruletas.id'], name='solicitudes_referido_ruleta_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='solicitudes_referido_pkey')
    )
    op.create_index('ix_solicitudes_referido_id', 'solicitudes_referido', ['id'], unique=False)
    op.create_index('ix_solicitudes_referido_email_referido', 'solicitudes_referido', ['email_referido'], unique=False)
    # ### end Alembic commands ###
