"""semana2_nuevos_modulos

Revision ID: 2254f80c205c
Revises: b083e4a816e0
Create Date: 2026-03-07 00:11:50.531144+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de revisión usados por Alembic
revision: str = '2254f80c205c'
down_revision: Union[str, None] = 'b083e4a816e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta migración a la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios de esta migración (rollback)."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
