"""tabla_administradores

Revision ID: 0aa6b6d161e6
Revises: 2254f80c205c
Create Date: 2026-03-23 17:10:00.364998+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identificadores de revisión usados por Alembic
revision: str = '0aa6b6d161e6'
down_revision: Union[str, None] = '2254f80c205c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta migración a la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crear tabla administradores
    op.create_table('administradores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('superadmin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ultimo_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='administradores_pkey'),
    sa.UniqueConstraint('email', name='administradores_email_key')
    )
    op.create_index('ix_administradores_username', 'administradores', ['username'], unique=True)
    op.create_index('ix_administradores_id', 'administradores', ['id'], unique=False)
    
    # Crear tabla solicitudes_referido
    op.create_table('solicitudes_referido',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referidor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email_referido', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('nombres_referido', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('ruleta_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estatus', postgresql.ENUM('pendiente', 'aprobado', 'rechazado', name='estatusreferido'), autoincrement=False, nullable=False),
    sa.Column('fecha_solicitud', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fecha_resolucion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='solicitudes_referido_cliente_id_fkey'),
    sa.ForeignKeyConstraint(['referidor_id'], ['clientes.id'], name='solicitudes_referido_referidor_id_fkey'),
    sa.ForeignKeyConstraint(['ruleta_id'], ['ruletas.id'], name='solicitudes_referido_ruleta_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='solicitudes_referido_pkey')
    )
    op.create_index('ix_solicitudes_referido_id', 'solicitudes_referido', ['id'], unique=False)
    op.create_index('ix_solicitudes_referido_email_referido', 'solicitudes_referido', ['email_referido'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios de esta migración (rollback)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_solicitudes_referido_email_referido', table_name='solicitudes_referido')
    op.drop_index('ix_solicitudes_referido_id', table_name='solicitudes_referido')
    op.drop_table('solicitudes_referido')
    op.drop_index('ix_administradores_username', table_name='administradores')
    op.drop_index('ix_administradores_id', table_name='administradores')
    op.drop_table('administradores')
    # ### end Alembic commands ###
