"""crear_tablas_iniciales

Revision ID: b083e4a816e0
Revises: 
Create Date: 2026-03-03 17:01:24.969384+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de revisión usados por Alembic
revision: str = 'b083e4a816e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta migración a la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agencias_id'), 'agencias', ['id'], unique=False)
    op.create_table('preguntas_seguridad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preguntas_seguridad_id'), 'preguntas_seguridad', ['id'], unique=False)
    op.create_table('ruletas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('max_giros', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ruletas_id'), 'ruletas', ['id'], unique=False)
    op.create_table('premios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ruleta_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cantidad_total', sa.Integer(), nullable=False),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=False),
    sa.Column('cantidad_entregada', sa.Integer(), nullable=True),
    sa.Column('porcentaje_prob', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('imagen_url', sa.String(length=255), nullable=True),
    sa.Column('es_condicionado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ruleta_id'], ['ruletas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premios_id'), 'premios', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agencia_id', sa.Integer(), nullable=True),
    sa.Column('nombres', sa.String(length=150), nullable=True),
    sa.Column('apellidos', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('celular', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('cargo', sa.String(length=150), nullable=True),
    sa.Column('fecha_acceso', sa.Date(), nullable=True),
    sa.Column('fecha_completo', sa.Date(), nullable=True),
    sa.Column('genero', sa.Enum('masculino', 'femenino', 'sin_dato', name='generocliente'), nullable=True),
    sa.Column('pregunta_seguridad_id', sa.Integer(), nullable=True),
    sa.Column('respuesta_seguridad', sa.Text(), nullable=True),
    sa.Column('premio_id', sa.Integer(), nullable=True),
    sa.Column('estatus', sa.Enum('anadido', 'registrado', 'participo', 'referido', 'referido_aprobado', 'referido_rechazado', name='estatuscliente'), nullable=True),
    sa.Column('token_usado', sa.Boolean(), nullable=True),
    sa.Column('referido_por_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agencia_id'], ['agencias.id'], ),
    sa.ForeignKeyConstraint(['pregunta_seguridad_id'], ['preguntas_seguridad.id'], ),
    sa.ForeignKeyConstraint(['premio_id'], ['premios.id'], ),
    sa.ForeignKeyConstraint(['referido_por_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_token'), 'clientes', ['token'], unique=True)
    op.create_table('premios_condicionados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('premio_id', sa.Integer(), nullable=False),
    sa.Column('email_cliente', sa.String(length=150), nullable=False),
    sa.Column('entregado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['premio_id'], ['premios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premios_condicionados_email_cliente'), 'premios_condicionados', ['email_cliente'], unique=False)
    op.create_index(op.f('ix_premios_condicionados_id'), 'premios_condicionados', ['id'], unique=False)
    op.create_table('correos_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('invitacion', 'felicitacion', 'referido', 'reenvio', name='tipocorreo'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'enviado', 'fallido', 'reenviado', name='estadocorreo'), nullable=True),
    sa.Column('asunto', sa.String(length=255), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('lote_id', sa.String(length=50), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correos_log_id'), 'correos_log', ['id'], unique=False)
    op.create_table('participaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('ruleta_id', sa.Integer(), nullable=False),
    sa.Column('premio_id', sa.Integer(), nullable=True),
    sa.Column('fecha_participacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('premio_entregado', sa.Boolean(), nullable=True),
    sa.Column('token_usado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['premio_id'], ['premios.id'], ),
    sa.ForeignKeyConstraint(['ruleta_id'], ['ruletas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participaciones_id'), 'participaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios de esta migración (rollback)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participaciones_id'), table_name='participaciones')
    op.drop_table('participaciones')
    op.drop_index(op.f('ix_correos_log_id'), table_name='correos_log')
    op.drop_table('correos_log')
    op.drop_index(op.f('ix_premios_condicionados_id'), table_name='premios_condicionados')
    op.drop_index(op.f('ix_premios_condicionados_email_cliente'), table_name='premios_condicionados')
    op.drop_table('premios_condicionados')
    op.drop_index(op.f('ix_clientes_token'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_premios_id'), table_name='premios')
    op.drop_table('premios')
    op.drop_index(op.f('ix_ruletas_id'), table_name='ruletas')
    op.drop_table('ruletas')
    op.drop_index(op.f('ix_preguntas_seguridad_id'), table_name='preguntas_seguridad')
    op.drop_table('preguntas_seguridad')
    op.drop_index(op.f('ix_agencias_id'), table_name='agencias')
    op.drop_table('agencias')
    # ### end Alembic commands ###
