"""crear_tablas_encuestas

Revision ID: 20dd799765dc
Revises: 4af89359fc7b
Create Date: 2026-04-06 18:38:04.318821+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de revisión usados por Alembic
revision: str = '20dd799765dc'
down_revision: Union[str, None] = '4af89359fc7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios de esta migración a la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios de esta migración (rollback)."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
